# comment
number = 1234
datetime = 2024-02-29T08:09:10

[section]
array = [
    1, 2, 3,
    7, 8, 9
]
multiline = """
the quick brown fox
jumped over the lazy dog
"""

[section.subsection]
key.subkey = "value"

[data]
d1 = -404
d2 = { type = "int" }
d3 = [
  "foo@example.com",
  { email = "bar@example.com", url = 'https://example.com/bar' },
  3.14
]

[data.constants]
max = inf
none = nan

[[fruits]]
name = "orange"
color = 0xFFA500

[[fruits]]
name = "apple"
color = 0xFF0000
